-- MySQL Script generated by MySQL Workbench
-- 03/18/17 16:30:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OrganizationalSystemDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OrganizationalSystemDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OrganizationalSystemDB` DEFAULT CHARACTER SET utf8 ;
USE `OrganizationalSystemDB` ;

-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `padre` INT NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(8) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  INDEX `fk_usuario_perfil_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `OrganizationalSystemDB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE usuario ADD inSession INT NOT NULL;
ALTER TABLE usuario ADD fechaNacimiento varchar(50) NOT NULL;
ALTER TABLE usuario ADD imagenPerfil varchar(100) NOT NULL;

-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `padre` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`),
  UNIQUE INDEX `idArea_UNIQUE` (`idArea` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `idArea` INT NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDireccion`),
  UNIQUE INDEX `idDireccion_UNIQUE` (`idDireccion` ASC),
  INDEX `fk_direccion_area_idx` (`idArea` ASC),
  CONSTRAINT `fk_direccion_area`
    FOREIGN KEY (`idArea`)
    REFERENCES `OrganizationalSystemDB`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Certificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Certificacion` (
  `idCertificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `avance` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCertificacion`),
  UNIQUE INDEX `idCertificacion_UNIQUE` (`idCertificacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`TareasCertificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`TareasCertificacion` (
  `idTareasCertificacion` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `idArea` INT NOT NULL,
  `idCertificacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idTareasCertificacion`),
  UNIQUE INDEX `idTareasCertificacion_UNIQUE` (`idTareasCertificacion` ASC),
  INDEX `fk_tarea_certificacion_idx` (`idCertificacion` ASC),
  INDEX `fk_tarea_area_idx` (`idArea` ASC),
  CONSTRAINT `fk_tarea_certificacion`
    FOREIGN KEY (`idCertificacion`)
    REFERENCES `OrganizationalSystemDB`.`Certificacion` (`idCertificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_area`
    FOREIGN KEY (`idArea`)
    REFERENCES `OrganizationalSystemDB`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Capacitacion` (
  `idCapacitacion` INT NOT NULL AUTO_INCREMENT,
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCapacitacion`),
  UNIQUE INDEX `idArea_UNIQUE` (`idCapacitacion` ASC),
  CONSTRAINT `fk_capacitacion_area`
    FOREIGN KEY (`idArea`)
    REFERENCES `OrganizationalSystemDB`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Meta` (
  `idMetas` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idDestinatario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMetas`),
  UNIQUE INDEX `idMetas_UNIQUE` (`idMetas` ASC),
  INDEX `fk_meta_usuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_meta_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `OrganizationalSystemDB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`Destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`Destinatario` (
  `idDestinatario` INT NOT NULL AUTO_INCREMENT,
  `idPerfil` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDestinatario`),
  UNIQUE INDEX `idDestinatario_UNIQUE` (`idDestinatario` ASC),
  CONSTRAINT `fk_destinatario_meta`
    FOREIGN KEY (`idDestinatario`)
    REFERENCES `OrganizationalSystemDB`.`Meta` (`idMetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizationalSystemDB`.`PerfilxArea`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `OrganizationalSystemDB`.`PerfilxArea` (
--   `idPerfil` INT NOT NULL,
--   `idArea` INT NOT NULL,
--   INDEX `fk_area_perfil_idx` (`idPerfil` ASC, `idArea` ASC),
--   INDEX `fk_perfil_area_idx` (`idArea` ASC),
--   CONSTRAINT `fk_perfil_area`
--     FOREIGN KEY (`idArea`)
--     REFERENCES `OrganizationalSystemDB`.`Perfil` (`idPerfil`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `fk_area_perfil`
--     FOREIGN KEY (`idPerfil` , `idArea`)
--     REFERENCES `OrganizationalSystemDB`.`Area` (`idArea` , `idArea`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `area`(`idArea`, `nombre`, `descripcion`, `padre`) VALUES (1,'Desarrollo','En esta área de la compañía se encuentran los desarrolladores de software pertenecientes a ésta',null);
INSERT INTO `perfil`(`idPerfil`, `idArea`, `nombre`, `descripcion`, `padre`) VALUES (1,1,'Administrador','Este perfil dispone de un control total del software de la compañía',null);
INSERT INTO `usuario`(`nombre`, `clave`, `correo`, `idPerfil`, `inSession`, `fechaNacimiento`, `imagenPerfil`) VALUES ('Jeison González Cifuentes', '123', 'jeison_gonzalez23161@elpoli.edu.co','1',0,'12/03/1999','/perfil.jgp');